# Generated by Django 3.1.2 on 2020-10-03 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0003_auto_20201003_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField(max_length=128, null=True)),
                ('symptoms', models.TextField(blank=True, max_length=256, null=True)),
                ('diagnosis', models.TextField(blank=True, max_length=256, null=True)),
                ('recomms', models.TextField(blank=True, max_length=256, null=True)),
                ('recipe', models.TextField(blank=True, max_length=256, null=True)),
                ('proc_date', models.DateField(auto_now_add=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Процедура',
                'verbose_name_plural': 'Процедуры',
            },
        ),
        migrations.CreateModel(
            name='OwnerProcedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=128, null=True)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('proc_date', models.DateField(auto_now_add=True, null=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Домашняя процедура',
                'verbose_name_plural': 'Домашние процедуры',
            },
        ),
    ]
