# Generated by Django 3.1.2 on 2020-10-13 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_auto_20201013_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprocedure',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ownerprocedure',
            name='name',
            field=models.TextField(max_length=128, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='ownerprocedure',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='ownerprocedure',
            name='proc_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='ownerprocedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='proc_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='purpose',
            field=models.TextField(max_length=128, null=True, verbose_name='Цель'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recipe',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recomms',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='symptoms',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Симптомы'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар'),
        ),
    ]
