# Generated by Django 3.1.2 on 2020-10-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20201013_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprocedure',
            name='proc_date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='proc_date',
            field=models.DateField(verbose_name='Дата'),
        ),
    ]
