# Generated by Django 3.1.2 on 2020-11-21 15:15

import cards.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cards', '0003_auto_20201029_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='VetAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=cards.models.vproc_att_directory_path, verbose_name='Фотография')),
                ('proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.procedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вложение Ветеринар',
                'verbose_name_plural': 'Вложения Ветеринар',
            },
        ),
        migrations.CreateModel(
            name='OwnerAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to=cards.models.oproc_att_directory_path, verbose_name='Фотография')),
                ('proc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.ownerprocedure')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вложение Владелец',
                'verbose_name_plural': 'Вложения Владелец',
            },
        ),
    ]
