# Generated by Django 3.1.2 on 2020-11-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_ownerattachment_vetattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='name',
            field=models.TextField(max_length=128, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='ownerprocedure',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='diagnosis',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recipe',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recomms',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='symptoms',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='Симптомы'),
        ),
    ]
