# Generated by Django 3.1.2 on 2020-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20201121_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprocedure',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='diagnosis',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recipe',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='recomms',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Рекомендации'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='symptoms',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Симптомы'),
        ),
    ]
