# Generated by Django 3.1.2 on 2020-11-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20201121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Название'),
        ),
    ]
