# Generated by Django 3.1.2 on 2020-10-19 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pets', '0004_auto_20201013_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_date', models.DateField(verbose_name='Время')),
                ('slot_time', models.TimeField(verbose_name='Дата')),
                ('purpose', models.TextField(blank=True, max_length=128, null=True, verbose_name='Цель')),
                ('appointed', models.BooleanField(blank=True, default=False, verbose_name='Занято')),
                ('pet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец')),
                ('vet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ветеринар')),
            ],
            options={
                'verbose_name': 'Слот',
                'verbose_name_plural': 'Слоты',
            },
        ),
    ]
