# Generated by Django 3.1.2 on 2020-11-21 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0010_auto_20201121_1841'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='pet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.pet', verbose_name='Питомец'),
        ),
        migrations.AlterField(
            model_name='slot',
            name='purpose',
            field=models.TextField(blank=True, max_length=128, null=True, verbose_name='Цель'),
        ),
    ]
