# Generated by Django 3.1.2 on 2020-10-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=64)),
                ('species', models.TextField(max_length=128)),
                ('color', models.TextField(max_length=128)),
                ('birth_date', models.DateField()),
                ('gender', models.TextField(max_length=10)),
                ('chip', models.TextField(max_length=64)),
                ('avatar', models.ImageField(null=True, upload_to='pavatars/')),
            ],
            options={
                'verbose_name': 'Питомец',
                'verbose_name_plural': 'Питомцы',
            },
        ),
    ]
