# Generated by Django 3.1.2 on 2020-10-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='pavatars/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='chip',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.TextField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.TextField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='name',
            field=models.TextField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.TextField(max_length=128, null=True),
        ),
    ]
