# Generated by Django 3.1.2 on 2020-10-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20201020_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Дата рождения'),
        ),
    ]
