# Generated by Django 3.1.2 on 2020-10-27 16:42

from django.db import migrations, models
import pets.models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20201021_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=pets.models.avatar_directory_path, verbose_name='Фотография'),
        ),
    ]
