# Generated by Django 3.1.2 on 2020-11-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0008_auto_20201121_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.TextField(blank=True, default='', max_length=10, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.TextField(blank=True, default='', max_length=128, null=True, verbose_name='Порода'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='chip',
            field=models.TextField(blank=True, default='', max_length=64, null=True, verbose_name='Чип'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.TextField(blank=True, default='', max_length=128, null=True, verbose_name='Окрас'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='contraindications',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Противопоказания'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.TextField(blank=True, default='', max_length=10, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Особые пометки'),
        ),
    ]
