# Generated by Django 3.1.2 on 2020-11-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0011_auto_20201121_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Вес'),
        ),
    ]
