# Generated by Django 3.1.2 on 2020-10-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
