# Generated by Django 3.1.2 on 2020-10-03 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201003_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
