# Generated by Django 3.1.2 on 2020-10-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201003_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uavatars/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, max_length=64, null=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='user',
            name='vet',
            field=models.BooleanField(default=False, verbose_name='Ветеринар'),
        ),
    ]
