# Generated by Django 3.1.2 on 2020-10-27 16:42

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201013_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.avatar_directory_path, verbose_name='Фотография'),
        ),
    ]
