# Generated by Django 3.1.2 on 2020-11-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201027_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='user',
            name='paid_service',
            field=models.BooleanField(default=False, verbose_name='Платные услуги'),
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AddField(
            model_name='user',
            name='super_vet',
            field=models.BooleanField(default=False, verbose_name='Владелец клиник'),
        ),
    ]
