# Generated by Django 3.1.2 on 2020-11-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20201121_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport',
            field=models.TextField(blank=True, default='', max_length=512, null=True, verbose_name='Паспортные данные'),
        ),
        migrations.AlterField(
            model_name='user',
            name='patronymic',
            field=models.TextField(blank=True, default='', max_length=64, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(blank=True, default='', max_length=64, null=True, verbose_name='Номер телефона'),
        ),
    ]
