# Generated by Django 3.1.2 on 2020-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201121_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='region',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='user',
            name='street',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.TextField(max_length=64, null=True, verbose_name='Номер телефона'),
        ),
    ]
